// src/components/FileTree.vue
<script setup lang="ts">
import { useTabStore } from '../stores/tabs'

console.log('[FileTree] Component loaded')

interface FileNode {
  name: string
  path: string
  isDir: boolean
  children: FileNode[]
  expanded: boolean
}

defineProps<{
  nodes: FileNode[]
  workingDirectory: string
}>()

const emit = defineEmits<{
  'open-file': [path: string]
  'toggle-node': [path: string]
}>()

const tabStore = useTabStore()

function toggleNode(node: FileNode) {
  console.log('[FileTree] toggleNode:', node.path)
  emit('toggle-node', node.path)
}

function openFile(node: FileNode) {
  console.log('[FileTree] openFile:', node.path)
  if (!node.isDir && node.name.endsWith('.md')) {
    emit('open-file', node.path)
  }
}

function isNodeActive(node: FileNode): boolean {
  if (!tabStore.activeTab) return false
  return tabStore.activeTab.path === node.path
}

function getNodeIcon(node: FileNode): string {
  if (node.isDir) {
    return node.expanded ? '📂' : '📁'
  }
  if (node.name.endsWith('.md')) return '📝'
  if (node.name.endsWith('.png') || node.name.endsWith('.jpg') || node.name.endsWith('.gif')) return '🖼️'
  if (node.name.endsWith('.json')) return '📋'
  if (node.name.endsWith('.py')) return '🐍'
  if (node.name.endsWith('.js') || node.name.endsWith('.ts')) return '📜'
  return '📄'
}
</script>

<template>
  <div class="file-tree">
    <template v-for="node in nodes" :key="node.path">
      <div 
        class="tree-node"
        :class="{ 
          directory: node.isDir,
          expanded: node.isDir && node.expanded,
          active: isNodeActive(node)
        }"
        @click="node.isDir ? toggleNode(node) : openFile(node)"
        @dblclick="openFile(node)"
      >
        <span class="node-icon">{{ getNodeIcon(node) }}</span>
        <span class="node-name">{{ node.name }}</span>
        <span v-if="node.isDir" class="expand-indicator">
          {{ node.expanded ? '▼' : '▶' }}
        </span>
      </div>
      
      <template v-if="node.isDir && node.expanded && node.children">
        <div class="children">
          <FileTree
            :nodes="node.children"
            :working-directory="workingDirectory"
            @open-file="emit('open-file', $event)"
            @toggle-node="emit('toggle-node', $event)"
          />
        </div>
      </template>
    </template>
  </div>
</template>

<style scoped>
.file-tree {
  padding: 4px 0;
}

.tree-node {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 12px;
  cursor: pointer;
  user-select: none;
  font-size: 14px;
  color: var(--text-primary);
  transition: all 0.15s ease;
}

.tree-node:hover {
  background: var(--sidebar-hover);
}

.tree-node.active {
  background: var(--sidebar-active);
  color: var(--primary-color);
}

.node-icon {
  font-size: 16px;
  width: 20px;
  text-align: center;
}

.node-name {
  flex: 1;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.expand-indicator {
  font-size: 10px;
  color: var(--text-secondary);
  width: 12px;
  text-align: center;
}

.children {
  border-left: 1px solid var(--border-color);
  margin-left: 16px;
  padding-left: 8px;
}
</style>

<script lang="ts">
export default {
  name: 'FileTree'
}
</script>

// src/components/FileTree.tsx
import { memo } from 'react'
import {
  ChevronRight,
  FileText,
  Folder,
  FolderOpen,
  Image,
  FileJson,
  FileCode,
} from 'lucide-react'
import { cn } from '../lib/utils'

export interface FileNode {
  name: string
  path: string
  isDir: boolean
  children: FileNode[]
  expanded: boolean
}

interface FileTreeProps {
  nodes: FileNode[]
  workingDirectory?: string
  activePath: string | null
  onOpenFile: (path: string) => void
  onToggleNode: (path: string) => void
}

function getNodeIcon(node: FileNode, expanded: boolean) {
  if (node.isDir) return expanded ? FolderOpen : Folder
  if (node.name.endsWith('.md')) return FileText
  if (/\.(png|jpg|jpeg|gif|svg)$/i.test(node.name)) return Image
  if (node.name.endsWith('.json')) return FileJson
  if (/\.(py|js|ts|tsx|rs)$/.test(node.name)) return FileCode
  return FileText
}

const TreeItem = memo(function TreeItem({
  node,
  depth,
  activePath,
  onOpenFile,
  onToggleNode,
}: {
  node: FileNode
  depth: number
  activePath: string | null
  onOpenFile: (path: string) => void
  onToggleNode: (path: string) => void
}) {
  const Icon = getNodeIcon(node, node.expanded)
  const isActive = !node.isDir && node.path === activePath

  return (
    <>
      <div
        role="button"
        tabIndex={0}
        className={cn(
          'flex items-center gap-2 py-1.5 pr-2 cursor-pointer select-none text-sm rounded-md transition-colors animate-fade-in',
          'text-[color:var(--color-text-primary)] hover:bg-[color:var(--color-sidebar-hover)]',
          isActive && 'bg-[color:var(--color-sidebar-active)] text-[color:var(--color-primary)]',
        )}
        style={{ paddingLeft: 8 + depth * 14 }}
        onClick={() => (node.isDir ? onToggleNode(node.path) : onOpenFile(node.path))}
        onKeyDown={(e) => {
          if (e.key === 'Enter') node.isDir ? onToggleNode(node.path) : onOpenFile(node.path)
        }}
      >
        {node.isDir ? (
          <ChevronRight
            size={13}
            className={cn(
              'shrink-0 text-[color:var(--color-text-tertiary)] transition-transform',
              node.expanded && 'rotate-90',
            )}
          />
          ) : (
            <span className="w-[13px] shrink-0" />
          )}
          <Icon
            size={15}
            className="shrink-0 text-[color:var(--color-text-secondary)]"
          />
        <span className="flex-1 truncate">{node.name}</span>
      </div>
      {node.isDir && node.expanded && node.children?.length > 0 && (
        <div className="border-l border-[color:var(--color-border-base)] ml-[14px] pl-1">
          {node.children.map((child) => (
            <TreeItem
              key={child.path}
              node={child}
              depth={depth + 1}
              activePath={activePath}
              onOpenFile={onOpenFile}
              onToggleNode={onToggleNode}
            />
          ))}
        </div>
      )}
    </>
  )
})

export default function FileTree({
  nodes,
  activePath,
  onOpenFile,
  onToggleNode,
}: FileTreeProps) {
  return (
    <div className="py-1">
      {nodes.map((node) => (
        <TreeItem
          key={node.path}
          node={node}
          depth={0}
          activePath={activePath}
          onOpenFile={onOpenFile}
          onToggleNode={onToggleNode}
        />
      ))}
    </div>
  )
}
