// src/components/Sidebar.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useTabStore } from '../stores/tabs'
import FileTree from './FileTree.vue'
import TabList from './TabList.vue'
import SettingsDialog from './SettingsDialog.vue'

console.log('[Sidebar] Component loaded')

const props = defineProps<{
  collapsed: boolean
}>()

const emit = defineEmits(['toggle', 'toggle-position'])

const tabStore = useTabStore()

console.log('[Sidebar] TabStore obtained, sidebarView:', tabStore.sidebarView)

const sidebarWidth = ref(280)

const currentView = computed(() => tabStore.sidebarView)

onMounted(() => {
  console.log('[Sidebar] onMounted, collapsed:', props.collapsed, 'currentView:', currentView.value)
})

function handleViewChange(view: 'tree' | 'tabs') {
  console.log('[Sidebar] handleViewChange called:', view)
  tabStore.setSidebarView(view)
}
</script>

<template>
  <div 
    class="sidebar" 
    :style="{ width: sidebarWidth + 'px' }"
  >
    <!-- 头部控制区 -->
    <div class="sidebar-header">
      <div class="header-left">
        <button 
          class="icon-btn" 
          @click="emit('toggle')"
          title="折叠侧边栏"
        >
          {{ props.collapsed ? '▶' : '◀' }}
        </button>
        <span class="sidebar-title">MDReader</span>
      </div>
      <div class="header-right">
        <button class="icon-btn" @click="emit('toggle-position')" title="切换侧边栏位置">
          ↭
        </button>
        <button class="icon-btn" @click="tabStore.refreshFileTree" title="刷新">
          🔄
        </button>
      </div>
    </div>

    <!-- 视图切换 -->
    <div class="view-switcher">
      <button
        class="view-btn"
        :class="{ active: currentView === 'tree' }"
        @click="handleViewChange('tree')"
      >
        <span>📁</span>
        <span>目录</span>
      </button>
      <button
        class="view-btn"
        :class="{ active: currentView === 'tabs' }"
        @click="handleViewChange('tabs')"
      >
        <span>📄</span>
        <span>页签</span>
      </button>
    </div>

    <!-- 视图内容 -->
    <div class="sidebar-content">
      <FileTree 
        v-if="currentView === 'tree'" 
        :nodes="tabStore.fileTree"
        :working-directory="tabStore.workingDirectory"
        @open-file="tabStore.openFile"
        @toggle-node="tabStore.toggleFileNode"
      />
      <TabList 
        v-else
        :tabs="tabStore.tabs"
        :active-tab-id="tabStore.activeTabId"
        @close-tab="tabStore.closeTab"
        @set-active="tabStore.setActiveTab"
        @new-tab="tabStore.newTab"
      />
    </div>

    <!-- 底部设置 -->
    <div class="sidebar-footer">
      <SettingsDialog />
    </div>
  </div>
</template>

<style scoped>
.sidebar {
  display: flex;
  flex-direction: column;
  background: var(--sidebar-bg);
  border-right: 1px solid var(--border-color);
  overflow: hidden;
}

.sidebar-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 8px;
  border-bottom: 1px solid var(--border-color);
  background: var(--sidebar-header-bg);
}

.header-left {
  display: flex;
  align-items: center;
  gap: 8px;
}

.sidebar-title {
  font-size: 14px;
  font-weight: 600;
  color: var(--text-primary);
}

.header-right {
  display: flex;
  gap: 4px;
}

.icon-btn {
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: transparent;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  color: var(--text-secondary);
  transition: all 0.15s ease;
}

.icon-btn:hover {
  background: var(--sidebar-hover);
  color: var(--text-primary);
}

.view-switcher {
  display: flex;
  gap: 4px;
  padding: 8px;
  border-bottom: 1px solid var(--border-color);
}

.view-btn {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  padding: 8px 12px;
  background: transparent;
  border: 1px solid transparent;
  border-radius: 6px;
  cursor: pointer;
  font-size: 13px;
  color: var(--text-secondary);
  transition: all 0.15s ease;
}

.view-btn:hover {
  background: var(--sidebar-hover);
}

.view-btn.active {
  background: var(--sidebar-active);
  border-color: var(--primary-color);
  color: var(--text-primary);
}

.sidebar-content {
  flex: 1;
  overflow-y: auto;
  overflow-x: hidden;
}

.sidebar-footer {
  padding: 8px;
  border-top: 1px solid var(--border-color);
}
</style>

// src/components/Sidebar.tsx
import {
  PanelLeftClose,
  PanelLeftOpen,
  ArrowLeftRight,
  RefreshCw,
  Folder,
  FileStack,
  Settings,
} from 'lucide-react'
import { cn } from '../lib/utils'
import FileTree, { type FileNode } from './FileTree'
import TabList, { type Tab } from './TabList'

interface SidebarProps {
  view: 'tree' | 'tabs'
  fileTree: FileNode[]
  tabs: Tab[]
  activeTabId: string | null
  workingDirectory: string
  activePath: string | null
  sidebarPosition: 'left' | 'right'
  onViewChange: (view: 'tree' | 'tabs') => void
  onCollapse: () => void
  onTogglePosition: () => void
  onRefreshTree: () => void
  onOpenFile: (path: string) => void
  onToggleNode: (path: string) => void
  onCloseTab: (id: string) => void
  onSetActiveTab: (id: string) => void
  onNewTab: () => void
  onOpenSettings: () => void
}

export default function Sidebar({
  view,
  fileTree,
  tabs,
  activeTabId,
  activePath,
  workingDirectory,
  sidebarPosition,
  onViewChange,
  onCollapse,
  onTogglePosition,
  onRefreshTree,
  onOpenFile,
  onToggleNode,
  onCloseTab,
  onSetActiveTab,
  onNewTab,
  onOpenSettings,
}: SidebarProps) {
  const width = 280

  return (
    <div
      className="flex flex-col h-full bg-[color:var(--color-sidebar)] border-[color:var(--color-border-base)] overflow-hidden"
      style={{
        width,
        borderRightWidth: sidebarPosition === 'left' ? 1 : 0,
        borderLeftWidth: sidebarPosition === 'right' ? 1 : 0,
      }}
    >
      {/* 头部 */}
      <div className="flex items-center justify-between px-2 py-2.5 border-b border-[color:var(--color-border-base)] bg-[color:var(--color-sidebar-header)]">
        <div className="flex items-center gap-2 min-w-0">
          <button
            className="icon-btn-28"
            onClick={onCollapse}
            title="折叠侧边栏"
          >
            {sidebarPosition === 'left' ? (
              <PanelLeftClose size={15} />
            ) : (
              <PanelLeftOpen size={15} />
            )}
          </button>
          <span className="text-sm font-semibold text-[color:var(--color-text-primary)] truncate">
            Ma读
          </span>
        </div>
        <div className="flex gap-1">
          <button className="icon-btn-28" onClick={onTogglePosition} title="切换侧边栏位置">
            <ArrowLeftRight size={14} />
          </button>
          <button className="icon-btn-28" onClick={onRefreshTree} title="刷新">
            <RefreshCw size={14} />
          </button>
        </div>
      </div>

      {/* 视图切换 */}
      <div className="flex gap-1 p-2 border-b border-[color:var(--color-border-base)]">
        <button
          className={cn(
            'flex-1 flex items-center justify-center gap-1.5 py-2 rounded-md text-[13px] transition-colors',
            'text-[color:var(--color-text-secondary)] hover:bg-[color:var(--color-sidebar-hover)]',
            view === 'tree' &&
              'bg-[color:var(--color-sidebar-active)] border border-[color:var(--color-primary)] text-[color:var(--color-text-primary)]',
          )}
          onClick={() => onViewChange('tree')}
        >
          <Folder size={14} />
          目录
        </button>
        <button
          className={cn(
            'flex-1 flex items-center justify-center gap-1.5 py-2 rounded-md text-[13px] transition-colors',
            'text-[color:var(--color-text-secondary)] hover:bg-[color:var(--color-sidebar-hover)]',
            view === 'tabs' &&
              'bg-[color:var(--color-sidebar-active)] border border-[color:var(--color-primary)] text-[color:var(--color-text-primary)]',
          )}
          onClick={() => onViewChange('tabs')}
        >
          <FileStack size={14} />
          页签
        </button>
      </div>

      {/* 视图内容 */}
      <div className="flex-1 overflow-y-auto overflow-x-hidden">
        {view === 'tree' ? (
          <FileTree
            nodes={fileTree}
            workingDirectory={workingDirectory}
            activePath={activePath}
            onOpenFile={onOpenFile}
            onToggleNode={onToggleNode}
          />
        ) : (
          <TabList
            tabs={tabs}
            activeTabId={activeTabId}
            onCloseTab={onCloseTab}
            onSetActive={onSetActiveTab}
            onNewTab={onNewTab}
          />
        )}
      </div>

      {/* 底部 */}
      <div className="p-2 border-t border-[color:var(--color-border-base)]">
        <button
          className="flex w-full items-center gap-2 px-3 py-2 rounded-md text-sm text-[color:var(--color-text-secondary)] hover:bg-[color:var(--color-sidebar-hover)] hover:text-[color:var(--color-text-primary)] transition-colors"
          onClick={onOpenSettings}
        >
          <Settings size={15} />
          设置
        </button>
      </div>
    </div>
  )
}
