// src/components/TabList.tsx
import { X, Plus, FileText } from 'lucide-react'
import { cn } from '../lib/utils'

export interface Tab {
  id: string
  path: string
  name: string
  content: string
  isModified: boolean
  isUntitled: boolean
}

interface TabListProps {
  tabs: Tab[]
  activeTabId: string | null
  onCloseTab: (id: string) => void
  onSetActive: (id: string) => void
  onNewTab: () => void
}

export default function TabList({
  tabs,
  activeTabId,
  onCloseTab,
  onSetActive,
  onNewTab,
}: TabListProps) {
  return (
    <div className="flex flex-col gap-1 py-2 max-h-full overflow-y-auto">
      {tabs.map((tab) => (
        <div
          key={tab.id}
          role="button"
          tabIndex={0}
          className={cn(
            'group flex items-center gap-2 px-3 py-2 cursor-pointer text-sm rounded-md transition-colors',
            'text-[color:var(--color-text-primary)] hover:bg-[color:var(--color-sidebar-hover)]',
            activeTabId === tab.id &&
              'bg-[color:var(--color-sidebar-active)] text-[color:var(--color-primary)]',
          )}
          onClick={() => onSetActive(tab.id)}
          onKeyDown={(e) => e.key === 'Enter' && onSetActive(tab.id)}
        >
          <FileText size={14} className="shrink-0 opacity-70" />
          <span className="flex-1 truncate" title={tab.name}>
            {tab.name}
          </span>
          {tab.isModified && (
            <span
              className="w-2 h-2 rounded-full bg-[color:var(--color-warning)] shrink-0"
              title="未保存"
            />
          )}
          <button
            className={cn(
              'w-5 h-5 flex items-center justify-center rounded transition-opacity',
              'text-[color:var(--color-text-secondary)] hover:bg-[color:var(--color-danger-bg)] hover:text-[color:var(--color-danger)]',
              'opacity-0 group-hover:opacity-100',
              activeTabId === tab.id && 'opacity-100',
            )}
            onMouseDown={(e) => e.preventDefault()}
            onClick={(e) => {
              e.stopPropagation()
              onCloseTab(tab.id)
            }}
            title="关闭"
          >
            <X size={13} />
          </button>
        </div>
      ))}
      <button
        className="flex items-center justify-center gap-1 py-2 text-[color:var(--color-text-secondary)] border-t border-[color:var(--color-border-base)] mt-1 hover:bg-[color:var(--color-sidebar-hover)] hover:text-[color:var(--color-primary)] transition-colors"
        onClick={onNewTab}
        title="新建页签"
      >
        <Plus size={15} />
      </button>
    </div>
  )
}

// src/components/TabList.vue
<script setup lang="ts">

interface Tab {
  id: string
  path: string
  name: string
  content: string
  isModified: boolean
  isUntitled: boolean
}

defineProps<{
  tabs: Tab[]
  activeTabId: string | null
}>()

const emit = defineEmits<{
  'close-tab': [id: string]
  'set-active': [id: string]
  'new-tab': []
}>()

function setActive(id: string) {
  emit('set-active', id)
}

function closeTab(e: MouseEvent, id: string) {
  e.preventDefault()
  emit('close-tab', id)
}

function newTab() {
  emit('new-tab')
}

function startRename(e: MouseEvent, tab: Tab) {
  e.preventDefault()
  // TODO: 实现重命名功能
  console.log('Rename:', tab)
}
</script>

<template>
  <div class="tab-list">
    <div 
      v-for="tab in tabs" 
      :key="tab.id"
      class="tab-item"
      :class="{ active: activeTabId === tab.id, modified: tab.isModified }"
      @click="setActive(tab.id)"
      @dblclick="(e: MouseEvent) => startRename(e, tab)"
    >
      <span class="tab-icon">{{ tab.isUntitled ? '➕' : '📄' }}</span>
      <span class="tab-name" :title="tab.name">{{ tab.name }}</span>
      <span v-if="tab.isModified" class="modified-dot" title="未保存"></span>
      <button 
        class="close-btn"
        @click="(e: MouseEvent) => closeTab(e, tab.id)"
        @mousedown.prevent
        title="关闭"
      >
        ×
      </button>
    </div>
    
    <div class="new-tab-btn" @click="newTab" title="新建页签">
      +
    </div>
  </div>
</template>

<style scoped>
.tab-list {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 8px 0;
  max-height: 100%;
  overflow-y: auto;
}

.tab-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  cursor: pointer;
  font-size: 13px;
  color: var(--text-primary);
  transition: all 0.15s ease;
}

.tab-item:hover {
  background: var(--sidebar-hover);
}

.tab-item.active {
  background: var(--sidebar-active);
  color: var(--primary-color);
}

.tab-icon {
  font-size: 14px;
  width: 18px;
  text-align: center;
}

.tab-name {
  flex: 1;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.modified-dot {
  width: 8px;
  height: 8px;
  background: var(--warning-color);
  border-radius: 50%;
  flex-shrink: 0;
}

.close-btn {
  width: 20px;
  height: 20px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: transparent;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
  line-height: 1;
  color: var(--text-secondary);
  opacity: 0;
  transition: all 0.15s ease;
}

.tab-item:hover .close-btn,
.tab-item.active .close-btn {
  opacity: 1;
}

.close-btn:hover {
  background: var(--danger-bg);
  color: var(--danger-color);
}

.new-tab-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 8px;
  cursor: pointer;
  color: var(--text-secondary);
  font-size: 18px;
  border-top: 1px solid var(--border-color);
  margin-top: 4px;
  transition: all 0.15s ease;
}

.new-tab-btn:hover {
  background: var(--sidebar-hover);
  color: var(--primary-color);
}
</style>
